---
fate:
    powers:
        - 
            name: Inhuman Strength
            description: "Blergh"
        - 
            name: Supernatural Strength
            description: "Hurgh"
        - 
            name: Mythic Strength
            description: "Gurgh"
        - 
            name: Inhuman Speed
            description: "Furgh"
        - 
            name: Supernatural Speed
            description: "Buh"
        - 
            name: Mythic Speed
            description: "Wat"

