---
secrets:
  database:
    password: ubrzvyaodcgekwsjilfpnqtxmh
  recaptcha:
    secret: ''
    site_key: ''
  aws:
    key_id: ''
    secret_key: ''
    bucket: ''
    region: ''
  gcse:
    search_id: ''
  engine_api_keys:
  - 8d922b71-88e4-4707-ac35-093e4e667161
